runtime: python37

#instance_class: F2

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/img
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'skop-project'